# Config Import
spring.config.import=optional:file:.env[.properties]

# Server
server.port=${PORT:8080}


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.database-platform=${DB_DIALECT}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# File Upload Limits
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# CORS
app.cors.allowed-origins=*

# JWT Secret
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# Cloudinary
app.cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
app.cloudinary.api-key=${CLOUDINARY_API_KEY}
app.cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Admin Credentials
app.admin.username=${ADMIN_USERNAME:admin}
app.admin.password=${ADMIN_PASSWORD:admin123}


